#!/bin/bash

title="Configs:"
widthpercent=10
config="~/.config/rofigen/cfgs/configs.rasi"


typeset -A menu
menu=(
    [bspwm]="alacritty -e vim .config/bspwm/bspwmrc"
    [polybar]="alacritty -e vim .config/polybar/config"
    [Picom]="alacritty -e vim .config/picom.conf"
    [Rofi]="alacritty -e vim .config/rofi/config.rasi"
)
