#!/bin/bash

title="Optimus Manager:"
widthpercent=10
config="~/.config/rofigen/cfgs/configs.rasi"
   
typeset -A menu

str="$(optimus-manager --status | grep 'Current GPU')"
echo $str
if [ "$str" = "Current GPU mode : intel" ]
then
	menu=(
		[Switch to NVIDIA ]="optimus-manager --switch nvidia --no-confirm"
		[Switch to Hybrid ]="optimus-manager --switch hybrid --no-confirm"
  )
elif [ "$str" = "Current GPU mode : nvidia" ]
then
	menu=(
		[Switch to Intel]="optimus-manager --switch intel --no-confirm" 
		[Switch to Hybrid ]="optimus-manager --switch hybrid --no-confirm"
	)   
elif [ "$str" = "Current GPU mode : hybrid" ]
then
	menu=(
		[Switch to Intel]="optimus-manager --switch intel --no-confirm"
		[Switch to NVIDIA ]="optimus-manager --switch nvidia --no-confirm" 
	)   
fi
