#!/bin/bash

title="Powermenu:"
widthpercent=10
config="~/.config/rofigen/cfgs/powermenu.rasi"


typeset -A menu
menu=(
    [Shutdown]="shutdown -h now"
    [Logout]="i3-msg exit"
    [Reboot]="reboot"
)